#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use mattstein\dekindler\ExtractCommand;

$application = new Application();

// ... register commands
$application->add(new ExtractCommand());
$application->run();
