#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use mattstein\utilities\ExtractKindleClippingsCommand;

$application = new Application();

// ... register commands
$application->add(new ExtractKindleClippingsCommand());
$application->run();
